s=read.table(file.choose(),header = TRUE,sep = ",",stringsAsFactors = TRUE)
View(s)
str(s)
summary(s)
View(s)
s1=na.omit(s)
View(s1)
str(s1)
summary(s1)
s$Sales[is.na(s$Sales)]=mean(s$Sales,na.rm=TRUE)
s$Sales
s$Profit[is.na(s$Profit)]=mean(s$Profit,na.rm=TRUE)
s$Unit.Price[is.na(s$Unit.Price)]=mean(s$Unit.Price,na.rm=TRUE)
s$Order.Quantity[is.na(s$Order.Quantity)]=mean(s$Order.Quantity,na.rm=TRUE)
s$Shipping.Cost[is.na(s$Shipping.Cost)]=mean(s$Shipping.Cost,na.rm=TRUE)
mod=function(x){
  x=na.omit(x)
  frequency_table=table(x)
  mode_values=names(frequency_table[frequency_table==max(frequency_table)])
  return(mode_values)
}
s$Order.Priority[is.na(s$Order.Priority)]=mod(s$Order.Priority)
s$Ship.Mode[is.na(s$Ship.Mode)]=mod(s$Ship.Mode)
s$Customer.Name[is.na(s$Customer.Name)]=mod(s$Customer.Name)
s$Customer.Segment[is.na(s$Customer.Segment)]=mod(s$Customer.Segment)
s$Product.Category[is.na(s$Product.Category)]=mod(s$Product.Category)
View(s)
s$company=NULL
View(s)
boxplot(s$Order.Quantity,main="Order Quantity")
boxplot(s$Sales,main="Sales")
boxplot(s$Shipping.Cost,main="Shipping.cost")
boxplot(s$Unit.Price,main="Unit.price")
boxplot(s$Profit,main="Profit")
summary(s1)
barplot(summary(s$Order.Priority),main="Priority")
barplot(summary(s$Product.Category),main="Product_category")
barplot(summary(s$Customer.Segment),main="customer_segment")
barplot(summary(s$Customer.Name),main="custermer_name")
s$Order.Priority[s$Order.Priority=="Loww"]="Low"
s$Order.Priority=droplevels(s$Order.Priority)
install.packages("DescTools")
library(DescTools)
#winserizer only use for integer
s$Order.Quantity=Winsorize(s$Order.Quantity)
s$Sales=Winsorize(s$Sales)
s$Shipping.Cost=Winsorize(s$Shipping.Cost)
s$Unit.Price=Winsorize(s$Unit.Price)
s$Profit=Winsorize(s$Profit)
boxplot(s$Order.Quantity,main="Order Quantity")
boxplot(s$Sales,main="Sales")
boxplot(s$Shipping.Cost,main="Shipping.cost")
boxplot(s$Unit.Price,main="Unit.price")
boxplot(s$Profit,main="Profit")
s$Order.Quantity
#staderdization of columns
scale(s$Order.Quantity,center = TRUE,scale = TRUE)
#min-max normalization
s$Order.Quantity=(s$Order.Quantity-min(s$Order.Quantity))/(max(s$Order.Quantity)-min(s$Order.Quantity))
s$Order.Quantity
min_max_nor=function(x){
  x=(x-min(x))/(max(x)-min(x))
  return(x)
}
s$Order.Quantity=min_max_nor(s$Order.Quantity)
s$Sales=min_max_nor(s$Sales)
s$Shipping.Cost=min_max_nor(s$Shipping.Cost)
s$Profit=min_max_nor(s$Profit)
s$Unit.Price=min_max_nor(s$Unit.Price)
View(s)
summary(s$Order.Quantity)
summary(s$Sales)
summary(s$Shipping.Cost)
summary(s$Profit)
summary(s$Unit.Price)
table(s$Order.Quantity)
table(s$Sales)
table(s$Shipping.Cost)
table(s$Profit)
table(s$Unit.Price)
#corelation

